<script lang="ts" setup>
import { DSCList } from "cdh-vue-lib";
import type { UUListTypes } from "cdh-vue-lib";
import { ref } from "vue";
import type { Pokemon } from "~/shared/mockData";

interface MyDSCListConfig {
    dataUri: string;
    sortEnabled: boolean;
    sortOptions?: UUListTypes.SortOption[];
    filtersEnabled: boolean;
    filters?: UUListTypes.FilterDefinition[];
    pageSize: number;
    pageSizeOptions: number[];
    searchEnabled: boolean;
    columns: UUListTypes.DataDefinedColumn[];
    container?: "default" | "sidebar";
}

const sampleConfig = ref<MyDSCListConfig>({
    dataUri: "/api/mockData",
    sortEnabled: true,
    sortOptions: [
        { field: "id", label: "ID" },
        { field: "name", label: "Name" },
        { field: "type", label: "Type" },
        { field: "height", label: "Height" },
    ],
    filtersEnabled: true,
    filters: [
        {
            field: "type",
            label: "Type",
            type: "checkbox",
            options: [
                ["Grass", "Grass"],
                ["Poison", "Poison"],
                ["Fire", "Fire"],
                ["Water", "Water"],
                ["Electric", "Electric"],
                ["Normal", "Normal"],
                ["Flying", "Flying"],
            ],
            initial: [],
        },
    ],
    pageSize: 5,
    pageSizeOptions: [3, 5, 10],
    searchEnabled: true,
    columns: [
        { field: "id", label: "ID", type: "string" },
        { field: "name", label: "Name", type: "string" },
        { field: "type", label: "Types", type: "string" },
        { field: "height", label: "Height", type: "string" },
    ],
    container: "default",
});
</script>

<template>
    <div class="container py-4">
        <section class="mb-4">
            <h1 class="mb-3">DSCList Component Documentation</h1>
            <p>
                The <code>DSCList</code> component is a specialized
                implementation of
                <NuxtLink to="/vue-lib-components/uu-list">UUList</NuxtLink>
                designed to work with a DSC (Django Shared Core) backend.
                Configuration (pagination, sorting, filtering, search) is
                handled through a single <code>config</code> prop generated by
                DSC.
            </p>
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Configuration (<code>config</code> prop)</h2>
            <p>
                The <code>config</code> prop is a reactive object that defines
                all aspects of the <code>DSCList</code> component's behavior and
                appearance.
            </p>

            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Property</th>
                            <th>Type</th>
                            <th>Required?</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><code>dataUri</code></td>
                            <td><code>string</code></td>
                            <td>Yes</td>
                            <td>
                                The URL of the API endpoint from which
                                <code>DSCList</code> will fetch data.
                            </td>
                        </tr>
                        <tr>
                            <td><code>columns</code></td>
                            <td>
                                <code>UUListTypes.DataDefinedColumn[]</code>
                            </td>
                            <td>Yes</td>
                            <td>
                                An array defining the columns for the default
                                <code>DataDefinedTable</code> visualizer. Each
                                object in the array typically specifies
                                <code>field</code> (data property),
                                <code>label</code> (column header), and
                                <code>type</code> (data type for rendering,
                                e.g., 'string', 'date').
                            </td>
                        </tr>
                        <tr>
                            <td><code>sortEnabled</code></td>
                            <td><code>boolean</code></td>
                            <td>Yes</td>
                            <td>Enables or disables sorting functionality.</td>
                        </tr>
                        <tr>
                            <td><code>sortOptions</code></td>
                            <td><code>UUListTypes.SortOption[]</code></td>
                            <td>No</td>
                            <td>
                                An array of objects (e.g.,
                                <code>{ field: string, label: string }</code>)
                                defining the available sort criteria if
                                <code>sortEnabled</code> is true.
                            </td>
                        </tr>
                        <tr>
                            <td><code>filtersEnabled</code></td>
                            <td><code>boolean</code></td>
                            <td>Yes</td>
                            <td>Enables or disables filtering.</td>
                        </tr>
                        <tr>
                            <td><code>filters</code></td>
                            <td><code>UUListTypes.FilterDefinition[]</code></td>
                            <td>No</td>
                            <td>
                                An array of
                                <code>FilterDefinition</code> objects to
                                configure the available filters.
                            </td>
                        </tr>
                        <tr>
                            <td><code>searchEnabled</code></td>
                            <td><code>boolean</code></td>
                            <td>Yes</td>
                            <td>
                                Enables or disables the global search input.
                            </td>
                        </tr>
                        <tr>
                            <td><code>pageSize</code></td>
                            <td><code>number</code></td>
                            <td>Yes</td>
                            <td>
                                The initial number of items to display per page.
                            </td>
                        </tr>
                        <tr>
                            <td><code>pageSizeOptions</code></td>
                            <td><code>number[]</code></td>
                            <td>Yes</td>
                            <td>
                                An array of numbers allowing the user to choose
                                different page sizes.
                            </td>
                        </tr>
                        <tr>
                            <td><code>container</code></td>
                            <td><code>"default" | "sidebar"</code></td>
                            <td>No</td>
                            <td>Specifies the overall layout container.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Slots</h2>
            <p>
                <code>DSCList</code> inherits and exposes the same slots as
                <code>UUList</code>, allowing for customization of its
                presentation:
            </p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <code>#data</code>: This is the primary slot for customizing
                    how the list items are rendered. If you provide content for
                    this slot, it will override the default
                    <code>DataDefinedTable</code> visualizer.
                </li>
                <li class="list-group-item">
                    <code>#filters-top</code>: Allows you to inject custom
                    content above the filter controls area.
                </li>
                <li class="list-group-item">
                    <code>#filters-bottom</code>: Allows you to inject custom
                    content below the filter controls area.
                </li>
            </ul>
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Basic example</h2>
            <p>
                To use <code>DSCList</code>, you provide a configuration object
                to its <code>config</code> prop. This object dictates the data
                source (API endpoint), available interactions (sorting,
                filtering, search), display settings (page size, columns), and
                overall layout.
            </p>
            <div class="card">
                <div class="card-body">
                    <DSCList :config="sampleConfig">
                        <template
                            #data="{
                                data,
                                isLoading,
                            }: {
                                data: Pokemon[];
                                isLoading: boolean;
                            }"
                        >
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Types</th>
                                        <th>Height</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-if="isLoading">
                                        <td colspan="4" class="text-center">
                                            Loading...
                                        </td>
                                    </tr>
                                    <tr v-else-if="data && data.length === 0">
                                        <td colspan="4" class="text-center">
                                            No items found.
                                        </td>
                                    </tr>
                                    <template v-else>
                                        <tr v-for="item in data" :key="item.id">
                                            <td>{{ item.id }}</td>
                                            <td>{{ item.name }}</td>
                                            <td>{{ item.type.join(", ") }}</td>
                                            <td>
                                                {{ item.height.toString() }}
                                            </td>
                                        </tr>
                                    </template>
                                </tbody>
                            </table>
                        </template>
                    </DSCList>
                </div>
            </div>
        </section>
    </div>
</template>
