<script lang="ts" setup>
import { DSCList, type UUListTypes } from "cdh-vue-lib";
import { ref } from "vue";
import PropTable, { type PropDefinition } from "~/components/PropTable.vue";
import SlotTable, { type SlotDefinition } from "~/components/SlotTable.vue";
import type { Pokemon } from "~/shared/mockData";

const sampleConfig = ref<UUListTypes.DSCListConfig>({
    dataUri: "/api/mockData",
    sortEnabled: true,
    sortOptions: [
        { field: "id", label: "ID" },
        { field: "name", label: "Name" },
        { field: "type", label: "Type" },
        { field: "height", label: "Height" },
    ],
    filtersEnabled: true,
    filters: [
        {
            field: "type",
            label: "Type",
            type: "checkbox",
            options: [
                ["Grass", "Grass"],
                ["Poison", "Poison"],
                ["Fire", "Fire"],
                ["Water", "Water"],
                ["Electric", "Electric"],
                ["Normal", "Normal"],
                ["Flying", "Flying"],
            ],
            initial: [],
        },
    ],
    pageSize: 5,
    pageSizeOptions: [3, 5, 10],
    searchEnabled: true,
    columns: [
        { field: "id", label: "ID", type: "string" },
        { field: "name", label: "Name", type: "string" },
        { field: "type", label: "Types", type: "string" },
        { field: "height", label: "Height", type: "string" },
    ],
    container: "default",
});

const propDefinitions: PropDefinition[] = [
    {
        name: "dataUri",
        type: "string",
        required: true,
        description:
            "The URL of the API endpoint from which DSCList will fetch data.",
    },
    {
        name: "columns",
        type: "UUListTypes.DataDefinedColumn[]",
        required: true,
        description:
            "An array defining the columns for the default DataDefinedTable visualizer. Each object in the array typically specifies field (data property), label (column header), and type (data type for rendering, e.g., 'string', 'date').",
    },
    {
        name: "sortEnabled",
        type: "boolean",
        required: true,
        description: "Enables or disables sorting functionality.",
    },
    {
        name: "sortOptions",
        type: "UUListTypes.SortOption[]",
        required: false,
        description:
            "An array of objects (of type { field: string; label: string; }) defining the available sort criteria if sortEnabled is true.",
    },
    {
        name: "filtersEnabled",
        type: "boolean",
        required: true,
        description: "Enables or disables filtering.",
    },
    {
        name: "filters",
        type: "UUListTypes.FilterDefinition[]",
        required: false,
        description:
            "An array of FilterDefinition objects to configure the available filters.",
    },
    {
        name: "searchEnabled",
        type: "boolean",
        required: true,
        description: "Enables or disables the global search input.",
    },
    {
        name: "pageSize",
        type: "number",
        required: true,
        description: "The initial number of items to display per page.",
    },
    {
        name: "pageSizeOptions",
        type: "number[]",
        required: true,
        description:
            "An array of numbers allowing the user to choose different page sizes.",
    },
    {
        name: "container",
        type: '"default" | "sidebar"',
        required: false,
        description: "Specifies the overall layout container.",
    },
];

const slotDefinitions: SlotDefinition[] = [
    {
        slotName: "data",
        description:
            "The primary slot for customizing how the list items are rendered. If you provide content for this slot, it will override the default DataDefinedTable visualizer.",
    },
    {
        slotName: "filters-top",
        description:
            "Allows you to inject custom content above the filter controls area.",
    },
    {
        slotName: "filters-bottom",
        description:
            "Allows you to inject custom content below the filter controls area.",
    },
];
</script>

<template>
    <div class="container py-4">
        <section class="mb-4">
            <h1 class="mb-3">DSCList Component Documentation</h1>
            <p>
                The <code>DSCList</code> component is a specialized
                implementation of
                <NuxtLink to="/vue-lib-components/uu-list">UUList</NuxtLink>
                designed to work with a DSC (Django Shared Core) backend.
                Configuration (pagination, sorting, filtering, search) is
                handled through a single <code>config</code> prop generated by
                DSC.
            </p>
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Configuration (<code>config</code> prop)</h2>
            <p>
                The <code>config</code> prop is a reactive object that defines
                all aspects of the <code>DSCList</code> component's behavior and
                appearance. The available properties for this object are as
                follows:
            </p>
            <PropTable :prop-defs="propDefinitions" />
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Slots</h2>
            <p>
                <code>DSCList</code> inherits and exposes the same slots as
                <code>UUList</code>, allowing for customization of its
                presentation:
            </p>
            <SlotTable :slot-defs="slotDefinitions" />
        </section>

        <section class="mb-4">
            <h2 class="mb-3">Basic example</h2>

            <DSCList :config="sampleConfig">
                <template
                    #data="{
                        data,
                        isLoading,
                    }: {
                        data: Pokemon[];
                        isLoading: boolean;
                    }"
                >
                    <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Types</th>
                                <th>Height</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-if="isLoading">
                                <td colspan="4" class="text-center">
                                    Loading...
                                </td>
                            </tr>
                            <tr v-else-if="data && data.length === 0">
                                <td colspan="4" class="text-center">
                                    No items found.
                                </td>
                            </tr>
                            <template v-else>
                                <tr v-for="item in data" :key="item.id">
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.type.join(", ") }}</td>
                                    <td>
                                        {{ item.height.toString() }}
                                    </td>
                                </tr>
                            </template>
                        </tbody>
                    </table>
                </template>
            </DSCList>
<pre class="code-example"><code>&lt;script lang="ts" setup&gt;
const sampleConfig: DSCListConfig = ref({
    dataUri: "/api/mockData",
    sortEnabled: true,
    sortOptions: [
        { field: "id", label: "ID" },
        { field: "name", label: "Name" },
        { field: "type", label: "Type" },
        { field: "height", label: "Height" },
    ],
    filtersEnabled: true,
    filters: [
        {
            field: "type",
            label: "Type",
            type: "checkbox",
            options: [
                ["Grass", "Grass"],
                ["Poison", "Poison"],
                ["Fire", "Fire"],
                ["Water", "Water"],
                ["Electric", "Electric"],
                ["Normal", "Normal"],
                ["Flying", "Flying"],
            ],
            initial: [],
        },
    ],
    pageSize: 5,
    pageSizeOptions: [3, 5, 10],
    searchEnabled: true,
    columns: [
        { field: "id", label: "ID", type: "string" },
        { field: "name", label: "Name", type: "string" },
        { field: "type", label: "Types", type: "string" },
        { field: "height", label: "Height", type: "string" },
    ],
    container: "default",
});
&lt;/script&gt;

&lt;template&gt;
    &lt;DSCList :config="sampleConfig"&gt;
        &lt;template
            #data="{data, isLoading}: { data: Pokemon[]; isLoading: boolean; }"
        &gt;
            &lt;table class="table table-hover"&gt;
                &lt;thead class="table-light"&gt;
                    &lt;tr&gt;
                        &lt;th&gt;ID&lt;/th&gt;
                        &lt;th&gt;Name&lt;/th&gt;
                        &lt;th&gt;Types&lt;/th&gt;
                        &lt;th&gt;Height&lt;/th&gt;
                    &lt;/tr&gt;
                &lt;/thead&gt;
                &lt;tbody&gt;
                    &lt;tr v-if="isLoading"&gt;
                        &lt;td colspan="4" class="text-center"&gt;
                            Loading...
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;tr v-else-if="data && data.length === 0"&gt;
                        &lt;td colspan="4" class="text-center"&gt;
                            No items found.
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;template v-else&gt;
                        &lt;tr v-for="item in data" :key="item.id"&gt;
                            &lt;td&gt;&lbrace;&lbrace; item.id &rbrace;&rbrace;&lt;/td&gt;
                            &lt;td&gt;&lbrace;&lbrace; item.name &rbrace;&rbrace;&lt;/td&gt;
                            &lt;td&gt;&lbrace;&lbrace; item.type.join(", ") &rbrace;&rbrace;&lt;/td&gt;
                            &lt;td&gt;
                                &lbrace;&lbrace; item.height.toString() &rbrace;&rbrace;
                            &lt;/td&gt;
                        &lt;/tr&gt;
                    &lt;/template&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
        &lt;/template&gt;
    &lt;/DSCList&gt;
&lt;/template&gt;</code></pre>
        </section>
    </div>
</template>
